# cluster_config.yml - cluster configuration
__default__:
    account: ctbrowngrp
    partition: low2 #bml
    job-name: "{rule}.w{wildcards}"
    logdir: "/home/ntpierce/2022-protein-kmers-workflow/slurm-logs"
#protein_AAI_via_compareM:
pyANI_ANIb:
    account: ctbrowngrp
    partition: bmm
    job-name: "{rule}.w{wildcards}"
    logdir: "/home/ntpierce/2022-protein-kmers-workflow/slurm-logs"

